# -*- mode: ruby -*-
# vi: set ft=ruby :

# Tạo máy ảo từ box centos/7, gán địa chỉ IP, đặt hostname, gán 2GB bộ nhớ, 2 cpus  
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.56.100"
    config.vm.hostname = "master.xtl"
    config.vbguest.auto_update = false
  
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end

    config.vm.provider "virtualbox" do |vb|
       vb.name = "master.xtl"
       vb.cpus = 2
       vb.memory = "2048"
    end
    
    # Chạy file install-docker-kube.sh sau khi nạp Box
    config.vm.provision "shell", path: "./../install-es-prd.sh"
  
    # Chạy các lệnh shell
    config.vm.provision "shell", inline: <<-SHELL
      # Đặt pass 123 có tài khoản root và cho phép SSH
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      sudo yum update -y 

      # fix loi khong tim thay kernel
      sudo yum install -y kernel-devel-$(uname -r)

      #Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
      sudo echo "192.168.56.100 master.xtl" >> /etc/hosts
      sudo echo "192.168.56.101 worker1.xtl" >> /etc/hosts
      sudo echo "192.168.56.102 worker2.xtl" >> /etc/hosts
      
    SHELL
  end